# Generated by Django 6.0.1 on 2026-01-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chantli', '0005_mensaje_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
