# Generated by Django 6.0.1 on 2026-01-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chantli', '0007_alter_reserva_estado_pago_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='pdf_factura',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
    ]
