# Generated by Django 6.0.1 on 2026-02-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chantli', '0008_alter_pago_pdf_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='acepto_terminos_y_reglamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='comprobante_domicilio_propiedad',
            field=models.FileField(blank=True, null=True, upload_to='documentos/propiedad/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='constancia_estudios_trabajo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/huesped/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='constancia_fiscal',
            field=models.FileField(blank=True, null=True, upload_to='documentos/fiscal/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='curp',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='direccion',
            field=models.TextField(blank=True, help_text='Dirección completa con CP'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='es_anfitrion_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='es_huesped_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_aceptacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='identificacion_frente',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/ids/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='identificacion_reverso',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/ids/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='referencia_nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='referencia_telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='requiere_deposito_garantia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rfc',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
