# Generated by Django 6.0.1 on 2026-02-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chantli', '0009_perfilusuario_acepto_terminos_y_reglamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='amenidades',
            field=models.TextField(blank=True, help_text='Lista de amenidades en formato JSON o texto'),
        ),
    ]
