# Generated by Django 6.0.1 on 2026-02-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chantli', '0012_resenausuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
